title: Hamilton
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: Yongfa Dai
avatar: /logo.png
email: yoinffa@outlook.com
email: daiyongfa@stu.gxmu.edu.cn
skin: daylight


plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: yoinffa
  card: summary
logo: logo.png
social:
  name: yoinffa
  links:
    - https://twitter.com/yoinffa
    - https://www.facebook.com/yoinffa
    - https://github.com/yoinffa
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
